version: '{build}'
configuration: Release
os: unstable

platform:
    - x86
    - x64

build_script:

    # Add required directories to path
    - cmd: set PATH=%PATH%;C:\MinGW\bin
    - cmd: set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin

    # Using GNU C Compiler (MinGW-compatible) on Windows
    - cmd: set MSYSTEM=MINGW64
    - cmd: gcc -o SendCommandMinGW64.exe SendCommand.c

    # Using Microsoft Visual Studio Compiler
    - cmd: call vcvars32.bat
    - cmd: cl.exe SendCommand.c

    # Now check both binaries
    - cmd: SendCommandMinGW64.exe --version
    - cmd: SendCommand.exe --version
